---
# Database connection string
connection_string: "postgres://trees:trees3r4t@localhost/treedbblue"

# Connection keep alive timeout [default: 75]
keep_alive: 75

# The socket address to bind [default: 0.0.0.0:3000]
listen_addresses: "127.0.0.1:3006"

# Maximum connections pool size [default: 20]
pool_size: 20

# Enable watch mode
watch: false

# Trust invalid certificates. 
# This introduces significant vulnerabilities, and should only be used as a last resort.
danger_accept_invalid_certs: false

# Number of web server workers
worker_processes: 8

# associative arrays of table sources
table_sources:
  public.treedata:
    # table source id
    id: public.treedata
    # table schema
    schema: treedb
    # table name
    table: treedata
    # geometry column name
    geometry_column: geom
    # geometry srid
    srid: 4326
    # tile extent in tile coordinate space
    extent: 4096
    # buffer distance in tile coordinate space to optionally clip geometries
    buffer: 64
    # boolean to control if geometries should be clipped or encoded as is
    clip_geom: false
    # geometry type
    geometry_type: POINT
    # list of columns, that should be encoded as tile properties
    properties:
      common: varchar
      city: varchar
      scientific: varchar
      health: varchar
      id: int4

# associative arrays of function sources
# function_sources:
#public.get_treedata:
    # function source id
    #   id: public.get_treedata
    # schema name
    #schema: public
    # function name
    #function: get_treedata
