version: '3'
services:
  martin:
    image: urbica/martin
    restart: unless-stopped
    ports:
      - 3000:3003
    environment:
      - WATCH_MODE=true
      - DATABASE_URL=postgres://trees@localhost/treedb
    depends_on:
      - db

  db:
    image: postgis/postgis:13-3.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=treedb
      - POSTGRES_USER=trees
      - POSTGRES_PASSWORD=
    volumes:
      - ./pg_data:/var/lib/postgresql/data
